name: CI

on: [workflow_call]

jobs:
  Test-Runner:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          cache: gradle
      - name: 'Tests: propactive-demo'
        run: make test-app
      - name: 'Uploading test artifacts'
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./build/test-results/test/*.xml
            ./build/reports
      - name: 'Klint: propactive-demo'
        run: make lint

  Test-Reporter:
    needs: Test-Runner
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Downloading all artifacts'
        uses: actions/download-artifact@v3
      - name: 'Generating test report for Github actions'
        uses: dorny/test-reporter@v1.5.0
        with:
          name: 'Test Report: JUnit'
          path: ./test-artifacts/test-results/test/*.xml
          reporter: java-junit
